steps:
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - functions
      - deploy
      - $_FUNCTION_NAME
      - --entry-point=$_ENTRY_POINT
      - --runtime=python37
      - --trigger-http
      - --project=$PROJECT_ID
      - --env-vars-file=$_ENV_YAML

substitutions:
  _FUNCTION_NAME: fm802-analysis
  _ENTRY_POINT: fm802_onair_info
  _ENV_YAML: env.yaml